version: "3.3"

services:
  python-parser:
    build:
      dockerfile: Dockerfile
      context: .
    command: python main.py
    volumes:
      - ./app:/home/app/
  postgres:
    image: postgres:10.5
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    ports:
     - '5432:5432'
    volumes: 
     - ./postgres-data:/var/lib/postgresql/data
