version: "3.3"
services:
  python-parser:
    build:
      dockerfile: Dockerfile
      context: .
    command: python main.py
    volumes:
      - ./app:/home/app/

  mongodb:
    image: mongo
    volumes:
      - ~/mongodb:/data/db
    ports:
      - "127.0.0.1:27017:27017"